fuma-nama/fumadocs

apps/docs/app/(home)/page.tsx

Added a grammatical correction.

Grammatical Correction in page.tsx

---

.changeset/smooth-buttons-run.md
packages/ui/src/components/api.tsx

CHANGED:
- Added a new colors for API info badge, so POST, PATCH requests are different from PUT.

UI: Added blue color to API Info component

---

.changeset/curvy-berries-behave.md
apps/docs/content/docs/ui/components/api/api-example.mdx
apps/docs/content/docs/ui/components/api/api-info.mdx
apps/docs/content/docs/ui/components/api/api.mdx
apps/docs/content/docs/ui/components/api/index.mdx
apps/docs/content/docs/ui/components/api/property.mdx
apps/docs/content/docs/ui/components/api/requests.mdx
apps/docs/content/docs/ui/components/api/responses.mdx
apps/docs/content/docs/ui/components/api/root.mdx
apps/docs/content/docs/ui/props.ts
packages/ui/src/components/api.tsx

UI: Documentation and updates to API components

---

.changeset/curly-knives-play.md
packages/create-app-versions/package.json
packages/create-app/src/create-app.ts
pnpm-lock.yaml

Fix the #709 issue, Now `@types/node` package install with `create fumasdocs-app`

Install the @types/node package

---

.changeset/eleven-rabbits-drive.md
packages/core/src/source/types.ts

thanks for the amazing project
fixes #843

fix(types): PageData MetaData exactOptionalPropertyTypes compat

---

apps/docs/content/docs/headless/search/trieve.mdx
apps/docs/content/docs/ui/search.mdx
examples/next-mdx/app/static.json/trieve.ts
examples/next-mdx/package.json
pnpm-lock.yaml

feature: add trieve search integration

---

apps/docs/content/docs/ui/manual-installation.mdx

Added Docker Deployment Section

---

.changeset/slimy-ads-deny.md
packages/core/package.json

Add dynamic-link export

---

apps/docs/content/blog/2024-5-15.mdx
apps/docs/content/docs/headless/mdx/structure.mdx
apps/docs/content/docs/headless/page-conventions.mdx
apps/docs/content/docs/headless/utils/index.mdx
apps/docs/content/docs/ui/mdx/heading.mdx
examples/openapi/openapi.json
packages/cli/src/commands/init.ts
packages/twoslash/styles/twoslash.css

fix: typos in multiple files

---

.changeset/hungry-cups-sneeze.md
packages/ui/css/ocean.css

Fixes the ocean theme to set the correct css variables.

UI: fix ocean theme

---

packages/ui/src/components/layout/toc.tsx
packages/ui/src/layouts/docs/sidebar.tsx

UI: fix TocPopover, Sidebar to work in react 18

---

apps/docs/content/docs/ui/index.mdx

I am closely observing your commits. I found typos, so I corrected them.

fix: typos, grammar

---

apps/docs/content/docs/ui/what-is-fumadocs.mdx

docs: fix typos

---

packages/ui/src/layouts/docs/shared.tsx

fix rootToggle errors #1611

---

.changeset/polite-stingrays-kick.md
packages/openapi/src/utils/get-pathname-from-input.ts

fix(#1717): add number type stringify for getPathnameFromInput

---

apps/docs/content/docs/ui/manual-installation.mdx

Display proper file title to the docs files

docs: add missing file title to code snippet

---

apps/docs/content/docs/ui/(integrations)/python.mdx

Closes #2048
| Before | After |
|-|-|
| ![image](https://github.com/user-attachments/assets/d1156873-0caf-48f8-951b-fec86416e821) | ![image](https://github.com/user-attachments/assets/121ae345-5206-4623-b1e3-ead352ed977d) |

docs(ui/python): eliminate typo on 'Experiemntal'

---

apps/docs/app/(home)/page.tsx

I hope this PR can resolve issue #2052.

fix(landing): add plural forms for grammatical correctness

---

apps/docs/app/(home)/sponsors/page.tsx
packages/openapi/CHANGELOG.md
packages/openapi/package.json
packages/openapi/src/media/adapter.ts

Reverts fuma-nama/fumadocs#2176

Revert "Sync"

---

apps/docs/components/ai/page-actions.tsx

Added [Scira AI](https://scira.ai) to AI Page actions

Add "Open in Scira AI" option to page actions

---

apps/docs/content/docs/ui/search/static.tsx
examples/next-mdx/app/api/search/route.ts
packages/create-app/template/+next/app/api/search/route.ts

#2189 some links were missed here

Update other instances of Orama Supported Languages link

---

packages/mdx/src/utils/import-formatter.ts
packages/mdx/test/fixtures/index-async.output.js
packages/mdx/test/fixtures/index-sync.output.js

Fixes: https://github.com/fuma-nama/fumadocs/issues/2205

fix: import ts file with `.js` extension

---

packages/ui/src/components/codeblock.tsx

Updates copy button to preserve the active state while in checked state.
BEFORE:
https://github.com/user-attachments/assets/b632e9b0-7f65-407e-8d40-0d77de151121
AFTER:
https://github.com/user-attachments/assets/de8ea4d9-d943-4f8e-8c15-c6375fe537bc

feat: Preserve accent when in checked state
