packages/next-docs-ui/src/components/toc.tsx, packages/next-docs-ui/src/page.tsx
We already got `footer`, so why not `header`.
Context: I'm using this header over at nextjs-faq.com, so...
=> Add support for TOC `header`

packages/next-docs-ui/src/components/mdx/pre.tsx
Previously, if you spam click the copy button it will still revert from "Copied" to "Copy" state 1.5s after the *first* click.
This refactors that logic to make the state change happen 1.5s after the *last* click which is the better behaviour IMO.
One less `useEffect`.
=> Improve <pre> copy button

.changeset/smooth-mugs-boil.md, packages/mdx/package.json
It ends up in the dist folder when bundled with tsup.
=> fix: Path to `next-docs-mdx/loader-mdx`

.changeset/proud-starfishes-switch.md, packages/openapi/package.json, packages/openapi/src/bin.ts, packages/openapi/src/generate-file.ts, packages/openapi/src/utils.ts, pnpm-lock.yaml
Added String | String[] patterns support to Input from config.
`./openapi/**/*.yaml`
used 2 dependencies:
glob, globby
cloud have used single one...
by checking if input path has pattern or not before resolving it cuts down a small portion of time.
`~15ms -> ~5ms`
=> Added patterns support to config Inputs.

packages/core/src/search/server.ts
Created an issue to track with at #280.
=> Remove default export from next/server.

apps/docs/content/docs/ui/index.mdx
This Pull Request adds guidance to a common problem a user might experience when using `Turborepo` with `Tailwindcss`. The issue is that by default in the Tailwind Config, will look for the `node_modules` containing `fumadocs/ui` which is needed for the styling with `DocsLayout`, which explains why the root page directing the user to go to `/docs` works with tailwind as expected. The fix is to edit `tailwind.config.js` and instead of `./node_modules`, it is `../../node_modules`.
This will add another accordion element to [Fumadocs FAQ](https://fumadocs.vercel.app/docs/ui#faq).
Thank you for Fumadocs.
> WillKirkmanM
=> FAQ: Turborepo Missing Styles Solution

packages/openapi/src/generate.ts
openapi generation doesn't have put method, just adding it
=> openapi add put method key

package.json, packages/openapi/src/generate.ts, packages/openapi/test/out/museum/events.mdx, packages/openapi/test/out/museum/operations.mdx, packages/openapi/test/out/museum/tickets.mdx
If `description` is multiple lines, this script would generate syntactically invalid frontmatter.
=> Fix multi-line frontmatter

apps/docs/content/docs/ui/search.mdx
I find a typo problem after copy and paste from documentation
Missing the 'd' word on search page at [UI docs](https://fumadocs.vercel.app/docs/ui/search#disable-search)
=> Docs: Fix typo enabled in search.mdx

packages/core/src/search/client.ts, packages/ui/src/components/dialog/search-default.tsx
Hello there! How are you doing?
Context:
I was working on a custom search implementation using the default implementation, which performs an API call for each search. To reduce the number of requests to the server, I wanted to increase the delayMs to a higher value. However, the current library does not provide a way to pass this parameter in the default implementation.
This PR aims to address that by allowing delayMs to be configurable.
=> Add configurable delayMs Parameter for Debounced Search Performance

.changeset/soft-masks-help.md, packages/ui/src/components/layout/link-item.tsx, packages/ui/src/layout.client.tsx, packages/ui/src/layout.tsx
Hello there!
I hope you're doing well.
I’d love to propose adding support for secondary custom links, allowing us to place additional content next to the existing GitHub URL for example. Instead of a basic link with a secondary type, I would like to include a customizable component right next to the other link.
I've implemented a solution to achieve this without impacting the current custom type. However, I would appreciate your feedback on whether this is the best approach or if we should consider enhancing the `custom` type property to include secondary on the `on` property.
Thank you for this amazing project! It has been incredibly beneficial for our work.
=> Adding secondary custom links

apps/docs/content/docs/headless/remote/github.mdx
There's an issue in the Setup of Remote MDX documentation here: https://fumadocs.vercel.app/docs/headless/remote/github#setup
The docs mention that the `accessToken` key must include the whole `Authorization` header content, including the `Bearer` prefix.
However, that is not necessary and causes builds to fail because FumaDocs internally adds the `Bearer` prefix in the `fetchTree` utility here:
https://github.com/fuma-nama/fumadocs/blob/16d06df180af5822fc59003488600b41195d083d/packages/mdx-remote/src/github/api/fetch-tree.ts#L56
The `Authorization` header content ends up being `Bearer Bearer <access-token>` and the builds fail.
=> Remove `Bearer` from `accessToken` in Remote MDX Docs

.changeset/three-countries-appear.md, packages/ui/src/components/layout/search-toggle.tsx, packages/ui/src/components/layout/theme-toggle.tsx, packages/ui/src/components/layout/toc.tsx
To enable custom styling of certain elements it is necessary to be able to target certain components and elements with CSS. Therefore we need to have uniqe classes or ids on these elements.
=> feat: add data attributes to relevant components for better css targeting

.changeset/shiny-maps-flash.md, packages/ui/package.json
Usage of the tailwind plugin (`fumadocs-ui/tailwind-plugin`) breaks the Tailwind CSS IntelliSense VSCode Extension. When included (i.e. in the default template), the following error message occurs:
```
[Error - 3:54:20 PM] Tailwind CSS: Default condition should be last one
Error: Default condition should be last one
at WU (/Users/adam/.vscode/extensions/bradlc.vscode-tailwindcss-0.12.5/dist/tailwindServer.js:134:11675)
at /Users/adam/.vscode/extensions/bradlc.vscode-tailwindcss-0.12.5/dist/tailwindServer.js:134:8936
at /Users/adam/.vscode/extensions/bradlc.vscode-tailwindcss-0.12.5/dist/tailwindServer.js:134:13933
at Zy.eval [as callAsync] (eval at create (/Users/adam/.vscode/extensions/bradlc.vscode-tailwindcss-0.12.5/dist/tailwindServer.js:5:78), <anonymous>:22:1)
at e.doResolve …
```
=> Fix bug breaking Tailwind CSS IntelliSense VSCode Extension

packages/openapi/src/ui/client.tsx
The copy route button doesn't have discernible text
=> small accessibility issue in `CopyRouteButton`

apps/docs/content/blog/v12.mdx, apps/docs/content/blog/v13.mdx, apps/docs/content/docs/headless/internationalization.mdx, apps/docs/content/docs/ui/comparisons.mdx, apps/docs/content/docs/ui/index.mdx, examples/i18n/content/docs/index.cn.mdx, examples/remote-mdx/content/docs/bry.mdx
Replaced `I18n` with `i18n` across the documents. I made sure to keep the functions named as it is.
=> Fixed typo for i18n across documents

packages/ui/src/page.tsx
If the page is an index page under the folder of the next level, it should be counted.
=> fix: DocsCategory should support dir index page

packages/openapi/src/ui/api/fetcher.ts, packages/openapi/src/ui/playground.tsx
- OpenAPI APIPlayground file upload is not working.
- Upload file and send in fumadocs `Buy museum tickets` example.
- Payload 'image' field has empty object.
- In the `createBodyFromValue` function, I found it resets FormData File field to empty {}. I add condition to set key if it's not File instance.
- For form-data, I changed it to not specify `Content-Type`. Fetch will automatically set it to `multipart/form-data`.
=> fix: openapi file upload feature

.changeset/quick-bears-refuse.md, packages/openapi/src/generate-file.ts, packages/openapi/test/fixtures/products.yaml, packages/openapi/test/index.test.ts
I maintain a OpenAPI 3.x spec that I'd like to document with Fumadocs, however I utilize multiple tags on several operations for automatic documentation organization purposes
Redoc supports multiple tags in their documentation generation out-of-the-box, and I think Fumadocs could benefit from the same
- Write the file for every tag for a given operation for `groupBy: 'tag'`
- Add test and test fixture
=> Support multiple tags in OpenAPI `groupBy: tag` file generation

apps/docs/content/docs/ui/comparisons.mdx
twoslash support was added in Nextra 3 and _meta.js files as well
=> Update comparisons.mdx. Update with Nextra 3 features

.changeset/chatty-balloons-approve.md, packages/openapi/src/render/schema.tsx, packages/openapi/src/utils/combine-schema.ts
Fixes https://github.com/fuma-nama/fumadocs/issues/1032
OpenAPI 3.0 marks an object as nullable by setting `nullable: true`. This can be set directly on the object, e.g.
```json
{
"type": "string",
"nullable": true
}
```
or it can be merged via `allOf`:
```json
{
"allOf": [
{ "type": "string" },
{ "nullable": true },
]
}
```
The current fumadocs-openapi renderer treats `anyOf` as similar to a TypeScript `&` operator. For example, the `anyOf` above would be rendered as `string & null` when it should be `string | null`.
To do:
=> Fix rendering of OpenAPI nullable defined with `allOf`.

.changeset/red-owls-grab.md, packages/openapi/src/ui/client.tsx, packages/openapi/src/ui/index.tsx
Aims to resolve https://github.com/fuma-nama/fumadocs/issues/1062
- OpenAPI
- feat: the server selector is now rendered only when the OpenAPI schema defines more than one server.
- fix: improved the `APIInfo` component's top positioning to improve visibility on smaller screens.
=> OpenAPI: Render Server Selector Only for Multiple Servers

apps/docs/content/docs/ui/(integrations)/mermaid.mdx
Resolves TypeScript error by moving MDX options to the correct configuration function. 
When using the existing example in a fresh clone, it will break. 
- Moved `mdxOptions` from `defineDocs` to `defineConfig` where it's properly supported
- Maintains Mermaid plugin functionality while fixing type errors
- Verified TypeScript compilation succeeds
- Confirmed Mermaid diagrams still render correctly
=> docs: fix mermaid example comment for fresh docs

apps/docs/content/docs/ui/(integrations)/open-graph.mdx, apps/docs/content/docs/ui/(integrations)/openapi/index.mdx
This pull request updates the documentation UI by adding tabs for different package managers to the OpenAPI and the Open Graph installation instructions.
OpenAPI Before:
OpenAPI After:
=> UI: Add Package Manager Tabs for OpenAPI and Open Graph

packages/ui/src/components/dialog/search.tsx
This fixes an issue where the tagslist will overflow when there are too much tags.
=> UI: fix tagslist not wrapping

apps/docs/content/docs/ui/components/tabs.mdx
Fix typo from `id` to `groupId`
=> Docs: Fix Typo in `Tab` Docs

.changeset/spotty-buckets-nail.md, packages/openapi/src/ui/playground/index.tsx
Hide the server select panel not just the select if no or only one server is present.
Changes: 
fix(packages/openapi): only show server select panel if servers exist
=> Fix: Hide the server select panel, not just the select, if no or only one server is present

.changeset/funny-kangaroos-do.md, packages/openapi/src/utils/generate-sample.ts
If no example value is defined for a parameter, keep the <> markers in the examples so that they are visible to the user.
changes:
- fix(packages/openapi): preserve <> placeholder marker for params with no example value
=> fix: openapi - preserve <> placeholder marker for params with no example value

.changeset/bright-jokes-sneeze.md, packages/openapi/src/render/operation.tsx
Hides Authorization if security config is empty, for example if there is a global default that's overwritten to empty (ie. webhooks)
Changes:
- fix(packages/openapi): hide AuthSection is security is an empty array
=> fix(packages/openapi): hide AuthSection is security is an empty array

.changeset/metal-cherries-ring.md, apps/docs/museum.yaml, packages/openapi/src/render/operation.tsx, packages/openapi/src/render/renderer.tsx, packages/openapi/src/requests/curl.ts, packages/openapi/src/requests/go.ts, packages/openapi/src/requests/javascript.ts, packages/openapi/src/requests/python.ts, packages/openapi/src/server/api-page.tsx, packages/openapi/src/utils/generate-sample.ts, packages/openapi/test/code-sample.test.ts, packages/openapi/test/fixtures/museum.yaml
Implements changes discussed in #1370 
Changes:
- show tabs if there are named examples
- show summary of examples as tab title
- show description of examples rendered as markdown
=> Feat: support multiple examples in openapi operation #1370

packages/openapi/src/render/schema.tsx
In OpenAPI V3.1 optional fields are commonly specified as `anyOf` in schema.
Example:
```json
"cursor": {"anyOf": [{"type": "string"}, {"type": "null"}]
```
this leads to sub-optimal display of types in docs:
This PR shows only the type option in case there is only one option to show.
=> OpenAPI: Improve display for anyOf schema type

.changeset/weak-books-smoke.md, packages/ui/src/components/github-info.tsx
For higher starred repositories show a humanized version for the star count instead of the full number
**Before**
**After**
=> feat(ui): add humanize stars to GitHub info component

apps/docs/content/docs/ui/(integrations)/open-graph.mdx
When executing the pnpm comand it returns an error (see image below). Adding `dlx` fix the error.
=> docs: fix pnpm command

apps/docs/content/docs/ui/customisation.mdx
This card links to https://fumadocs.vercel.app/docs/ui/layouts/home (404)
when it should be https://fumadocs.vercel.app/docs/ui/layouts/home-layout
=> (docs) fix: deadlink in customisation.mdx

.changeset/five-pears-sort.md, packages/ui/src/page-client.tsx
Currently, in the footer navigation, if the description is not present, the button to go to the previous page is labeled "Next".
This PR will fix this to use a proper label for this button.
=> UI: Use `text.previousPage` for previous page navigation

apps/docs/app/llms.txt/route.ts
Currently the description at https://fumadocs.vercel.app/llms.txt is:
```
file: ./content/docs/cli/index.mdx
The CLI tool that automates setups and installing components.
[object Promise]
file: ./content/docs/headless/custom-source.mdx
Build your own content source
[object Promise]
```
because the promise for `processor.process` is not being awaited. This is a minor fix
=> fix(llms.txt): Await remark processor

.changeset/heavy-trees-move.md, packages/create-app/tsup.config.ts
- Updated the tsup configuration to generate declaration files with `dts: true`
=> fix: enable TypeScript declaration generation for create-fumadocs-app

examples/i18n/app/[lang]/(home)/page.tsx, examples/i18n/app/layout.config.tsx
Fixes the jump links in i18n examples to make them more user-friendly. 
The changes include:
1. Improved navigation links.
2. Improved hero-to-documentation link.
=> Docs: Improve i18n link

.changeset/shaggy-actors-worry.md, packages/python/pyproject.toml
```python
python $ uv run fumapy-generate pathlib
Traceback (most recent call last):
File "/Users/stacia/Documents/GitHub/fumadocs/packages/python/.venv/bin/fumapy-generate", line 4, in <module>
from fumapy import generate
File "/Users/stacia/Documents/GitHub/fumadocs/packages/python/fumapy/__init__.py", line 6, in <module>
from griffe_typingdoc import TypingDocExtension
ModuleNotFoundError: No module named 'griffe_typingdoc'
```
https://github.com/fuma-nama/fumadocs/blob/3372792d4755113f6f2e5316b71593fa0f8d7b4e/packages/python/fumapy/__init__.py#L6
=> Fix: fumadocs-python missing `griffe-typingdoc` dependency

examples/react-router/app/docs/page.tsx
According to [RR docs](https://reactrouter.com/start/framework/route-module#meta), `<meta />` is recommended since React 19, and can better inject metadata from markdown.
=> chore(example/react-router): use meta element in docs page

packages/ui/src/components/layout/toc-clerk.tsx
Updates the Table of Contents links to use `hover:text-fd-foreground` for hover states. This ensures visual consistency with the design system's foreground color, improving readability and user experience during interaction.
=> fix(toc): apply consistent hover color using `hover:text-fd-foreground`

.changeset/short-candies-greet.md, packages/openapi/src/requests/javascript.ts, packages/openapi/test/out/samples/1.js
Currently JS code examples generated by the OpenAPI integration lack the `method` option and the `Content-Type` header inside the `fetch`.
This PR adds them. What would previously be: 
```js
const body = JSON.stringify({
"name": "Marc",
"email": "marc@scalar.com",
"password": "i-love-scalar"
})
fetch("https://galaxy.scalar.com/user/signup", {
body
})
```
Is now: 
```js
const body = JSON.stringify({
"name": "Marc",
"email": "marc@scalar.com",
"password": "i-love-scalar"
})
fetch("https://galaxy.scalar.com/user/signup", {
method: "POST",
headers: {
"Content-Type": "application/json"
},
body
})
```
=> Add `Content-Type` header & `method` option to OpenAPI JavaScript code example

.changeset/loud-apples-stay.md, packages/ui/src/components/dialog/search.tsx
When using CJK IMEs, text stays in a composition state until it is committed.
Typical IME keys:
- <kbd>Enter</kbd>: commits the current composition
- <kbd>↑</kbd> / <kbd>↓</kbd>: cycles through candidate words
Because the search dialog listens for these same keys, it may:
- open the first result when the user presses <kbd>Enter</kbd> to commit text
- jump the highlight when the user <kbd>↑</kbd> / <kbd>↓</kbd> to pick a candidate
This PR guards the keydown handler with [isComposing](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/isComposing), so IME composition keys are ignored and the dialog no longer hijacks them.
=> fix: ignore IME composition to avoid accidental selection

apps/docs/app/(home)/page.tsx, apps/docs/content/docs/headless/custom-source.mdx
Closes #2053.
| Before | After |
|-|-|
| <img width="640" height="713" alt="image" src="https://github.com/user-attachments/assets/1ea440f8-c8ee-4df7-9d4e-069c43e19fa7" /> | <img width="619" height="702" alt="image" src="https://github.com/user-attachments/assets/145382c0-fc8c-404b-8993-716955a18d6a" /> |
| <img width="193" height="232" alt="image" src="https://github.com/user-attachments/assets/d30dcaad-013e-4909-83d8-c5da7dc97aac" /> | <img width="176" height="268" alt="image" src="https://github.com/user-attachments/assets/cd210259-aabe-466f-b72f-2dea9566507e" /> |
- Kept the template as clean and minimal as possible
- Used SQLite instead of PostgreSQL or MongoDB to lower the learning curve for beginners & save them from the headache of having to set up a database
- Kept the README …
=> 📚️ docs(headless/custom-source/examples): add payload cms

apps/docs/lib/metadata.ts
This change ensures that links point to the right url on production env. e.g. if you look at the sitemap.xml file you can see that all urls in it are incorrectly pointed to the temporary vercel deployment url: https://fumadocs.dev/sitemap.xml This will make the sitemap be pointed to the right url fumadocs.dev and in turn help google discover the website content.
=> fix: ensure metadata points to production url

apps/docs/content/docs/headless/page-conventions.mdx
I'm not sure when this was removed or if there was a specific reason for it, but I did some digging and found that the functionality did exist. So I decided to add it back to the docs
=> Docs: Add 'Except' item to Routing docs

.changeset/whole-ghosts-laugh.md, packages/create-app/template/react-router/app/docs/search.ts, packages/create-app/template/react-router/app/lib/source.ts
Resolves #2295 and resolves another import error in packages/create-app/template/react-router/app/docs/search.ts.
=> Fix React Router template imports

.changeset/chilled-bikes-think.md, packages/openapi/src/generate-file.ts
Reference documentation: [openapi/configurations](https://fumadocs.dev/docs/ui/openapi/configurations#index)  
Previous version logic: When the page frontmatter does not contain a description, the Card Component would display:  
```
<Card href="/docs/api_endpoint" title="title" description=undefined />
```  
This would cause a page compilation error.  
This PR fixes the issue.  
Additionally: The description field from my OpenAPI Schema does not seem to be included in the frontmatter. Instead, it is placed under:  
```
_openapi:
method: GET
route: /tasks/{task_id}
toc: []
structuredData:
headings: []
contents:
- content: {{MY_DESCRIPTION}}
```  
Is this the expected behavior or a bug?  
I would be happy to submit further PRs. Thank you!
=> OpenAPI: handle undefined description in index.md generation

apps/docs/content/blog/make-a-blog.mdx, apps/docs/content/blog/mdx-v10-summary.mdx, apps/docs/content/blog/mdx-v10.mdx, apps/docs/lib/source.ts, examples/i18n/lib/source.ts, examples/openapi/lib/source.ts, packages/mdx/src/index.ts, packages/mdx/src/next/map/generate.ts
the builds were failing with the updated index export in df7e0a6cb1d0d5ecdd4a8a809462d890ed0853b0. updated the imports to fix the build
=> chore: point createMDXSource imports to runtime/next

packages/ui/src/components/ui/button.tsx
Add missing ring classes for buttonVariants to ensure focus states are visible for buttons.
https://github.com/user-attachments/assets/0a192664-abde-4914-8ff9-4e72a03489ab
=> fix: Add focus ring to buttonVariants
